// Automatically generated by https://honeythecodewitch.com/gfx/icon-pack
// #define PIECE_IMPLEMENTATION in exactly one
// translation unit (.cpp file) before including this header
#ifndef PIECE_HPP
#define PIECE_HPP
#include <stdint.h>
#include <stddef.h>
#include "gfx_core.hpp"
#include "gfx_positioning.hpp"

constexpr static const uint16_t piece_height = 32;

/// @brief "Chess Bishop" dimensions
constexpr static const gfx::sizef piece_chess_bishop_dimensions(320,512);
/// @brief "Chess Bishop" scaled dimensions
constexpr static const gfx::size16 piece_chess_bishop_scaled_dimensions(20,32);
/// @brief "Chess Bishop" target scale
constexpr static const float piece_chess_bishop_scale = 0.0625;
/// @brief "Chess Bishop" - a SVG vector icon
extern gfx::const_buffer_stream piece_chess_bishop;
/// @brief "Chess Bishop" dimensions
constexpr static const gfx::sizef piece_chess_bishop2_dimensions(320,512);
/// @brief "Chess Bishop" scaled dimensions
constexpr static const gfx::size16 piece_chess_bishop2_scaled_dimensions(20,32);
/// @brief "Chess Bishop" target scale
constexpr static const float piece_chess_bishop2_scale = 0.0625;
/// @brief "Chess Bishop" - a SVG vector icon
extern gfx::const_buffer_stream piece_chess_bishop2;
/// @brief "Chess King" dimensions
constexpr static const gfx::sizef piece_chess_king_dimensions(448,512);
/// @brief "Chess King" scaled dimensions
constexpr static const gfx::size16 piece_chess_king_scaled_dimensions(28,32);
/// @brief "Chess King" target scale
constexpr static const float piece_chess_king_scale = 0.0625;
/// @brief "Chess King" - a SVG vector icon
extern gfx::const_buffer_stream piece_chess_king;
/// @brief "Chess King" dimensions
constexpr static const gfx::sizef piece_chess_king2_dimensions(448,512);
/// @brief "Chess King" scaled dimensions
constexpr static const gfx::size16 piece_chess_king2_scaled_dimensions(28,32);
/// @brief "Chess King" target scale
constexpr static const float piece_chess_king2_scale = 0.0625;
/// @brief "Chess King" - a SVG vector icon
extern gfx::const_buffer_stream piece_chess_king2;
/// @brief "Chess Knight" dimensions
constexpr static const gfx::sizef piece_chess_knight_dimensions(448,512);
/// @brief "Chess Knight" scaled dimensions
constexpr static const gfx::size16 piece_chess_knight_scaled_dimensions(28,32);
/// @brief "Chess Knight" target scale
constexpr static const float piece_chess_knight_scale = 0.0625;
/// @brief "Chess Knight" - a SVG vector icon
extern gfx::const_buffer_stream piece_chess_knight;
/// @brief "Chess Knight" dimensions
constexpr static const gfx::sizef piece_chess_knight2_dimensions(448,512);
/// @brief "Chess Knight" scaled dimensions
constexpr static const gfx::size16 piece_chess_knight2_scaled_dimensions(28,32);
/// @brief "Chess Knight" target scale
constexpr static const float piece_chess_knight2_scale = 0.0625;
/// @brief "Chess Knight" - a SVG vector icon
extern gfx::const_buffer_stream piece_chess_knight2;
/// @brief "Chess Pawn" dimensions
constexpr static const gfx::sizef piece_chess_pawn_dimensions(320,512);
/// @brief "Chess Pawn" scaled dimensions
constexpr static const gfx::size16 piece_chess_pawn_scaled_dimensions(20,32);
/// @brief "Chess Pawn" target scale
constexpr static const float piece_chess_pawn_scale = 0.0625;
/// @brief "Chess Pawn" - a SVG vector icon
extern gfx::const_buffer_stream piece_chess_pawn;
/// @brief "Chess Pawn" dimensions
constexpr static const gfx::sizef piece_chess_pawn2_dimensions(320,512);
/// @brief "Chess Pawn" scaled dimensions
constexpr static const gfx::size16 piece_chess_pawn2_scaled_dimensions(20,32);
/// @brief "Chess Pawn" target scale
constexpr static const float piece_chess_pawn2_scale = 0.0625;
/// @brief "Chess Pawn" - a SVG vector icon
extern gfx::const_buffer_stream piece_chess_pawn2;
/// @brief "Chess Queen" dimensions
constexpr static const gfx::sizef piece_chess_queen_dimensions(512,512);
/// @brief "Chess Queen" scaled dimensions
constexpr static const gfx::size16 piece_chess_queen_scaled_dimensions(32,32);
/// @brief "Chess Queen" target scale
constexpr static const float piece_chess_queen_scale = 0.0625;
/// @brief "Chess Queen" - a SVG vector icon
extern gfx::const_buffer_stream piece_chess_queen;
/// @brief "Chess Queen" dimensions
constexpr static const gfx::sizef piece_chess_queen2_dimensions(512,512);
/// @brief "Chess Queen" scaled dimensions
constexpr static const gfx::size16 piece_chess_queen2_scaled_dimensions(32,32);
/// @brief "Chess Queen" target scale
constexpr static const float piece_chess_queen2_scale = 0.0625;
/// @brief "Chess Queen" - a SVG vector icon
extern gfx::const_buffer_stream piece_chess_queen2;
/// @brief "Chess Rook" dimensions
constexpr static const gfx::sizef piece_chess_rook_dimensions(448,512);
/// @brief "Chess Rook" scaled dimensions
constexpr static const gfx::size16 piece_chess_rook_scaled_dimensions(28,32);
/// @brief "Chess Rook" target scale
constexpr static const float piece_chess_rook_scale = 0.0625;
/// @brief "Chess Rook" - a SVG vector icon
extern gfx::const_buffer_stream piece_chess_rook;
/// @brief "Chess Rook" dimensions
constexpr static const gfx::sizef piece_chess_rook2_dimensions(448,512);
/// @brief "Chess Rook" scaled dimensions
constexpr static const gfx::size16 piece_chess_rook2_scaled_dimensions(28,32);
/// @brief "Chess Rook" target scale
constexpr static const float piece_chess_rook2_scale = 0.0625;
/// @brief "Chess Rook" - a SVG vector icon
extern gfx::const_buffer_stream piece_chess_rook2;
#endif // PIECE_HPP

#ifdef PIECE_IMPLEMENTATION
static const char* piece_chess_bishop_data = "<svg xmlns=\"http://www.w3.org/2000/svg\""
    " viewBox=\"0 0 320 512\"><path d=\"M128 0C110.3 0 96 14.3 96 32c0 16.1 11.9 29.4 27"
    ".4 31.7C78.4 106.8 8 190 8 288c0 47.4 30.8 72.3 56 84.7L64 400l192 0 0-27.3c25.2"
    "-12.5 56-37.4 56-84.7c0-37.3-10.2-72.4-25.3-104.1l-99.4 99.4c-6.2 6.2-16.4 6.2-2"
    "2.6 0s-6.2-16.4 0-22.6L270.8 154.6c-23.2-38.1-51.8-69.5-74.2-90.9C212.1 61.4 224"
    " 48.1 224 32c0-17.7-14.3-32-32-32L128 0zM48 432L6.6 473.4c-4.2 4.2-6.6 10-6.6 16"
    "C0 501.9 10.1 512 22.6 512l274.7 0c12.5 0 22.6-10.1 22.6-22.6c0-6-2.4-11.8-6.6-1"
    "6L272 432 48 432z\"/></svg>";
gfx::const_buffer_stream piece_chess_bishop
    ((const uint8_t*)piece_chess_bishop_data, 545);

static const char* piece_chess_bishop2_data = "<svg xmlns=\"http://www.w3.org/2000/svg"
    "\" viewBox=\"0 0 320 512\"><path d=\"M104 0C90.7 0 80 10.7 80 24c0 11.2 7.6 20.6 18 "
    "23.2c-7.8 8-16.1 17-24.4 27C38.2 116.7 0 178.8 0 250.9c0 44.8 24.6 72.2 48 87.8L"
    "48 352l48 0 0-27c0-9-5-17.2-13-21.3c-18-9.3-35-24.7-35-52.7c0-55.5 29.8-106.8 62"
    ".4-145.9c16-19.2 32.1-34.8 44.2-45.5c1.9-1.7 3.7-3.2 5.3-4.6c1.7 1.4 3.4 3 5.3 4"
    ".6c12.1 10.7 28.2 26.3 44.2 45.5c5.3 6.3 10.5 13 15.5 20L159 191c-9.4 9.4-9.4 24"
    ".6 0 33.9s24.6 9.4 33.9 0l57.8-57.8c12.8 25.9 21.2 54.3 21.2 83.8c0 28-17 43.4-3"
    "5 52.7c-8 4.1-13 12.3-13 21.3l0 27 48 0 0-13.3c23.4-15.6 48-42.9 48-87.8c0-72.1-"
    "38.2-134.2-73.6-176.7c-8.3-9.9-16.6-19-24.4-27c10.3-2.7 18-12.1 18-23.2c0-13.3-1"
    "0.7-24-24-24L160 0 104 0zM52.7 464l16.6-32 181.6 0 16.6 32L52.7 464zm207.9-80l-2"
    "01 0c-12 0-22.9 6.7-28.4 17.3L4.6 452.5c-3 5.8-4.6 12.2-4.6 18.7C0 493.8 18.2 51"
    "2 40.8 512l238.5 0c22.5 0 40.8-18.2 40.8-40.8c0-6.5-1.6-12.9-4.6-18.7l-26.5-51.2"
    "c-5.5-10.6-16.5-17.3-28.4-17.3z\"/></svg>";
gfx::const_buffer_stream piece_chess_bishop2
    ((const uint8_t*)piece_chess_bishop2_data, 958);

static const char* piece_chess_king_data = "<svg xmlns=\"http://www.w3.org/2000/svg\" v"
    "iewBox=\"0 0 448 512\"><path d=\"M224 0c17.7 0 32 14.3 32 32l0 16 16 0c17.7 0 32 14"
    ".3 32 32s-14.3 32-32 32l-16 0 0 48 152 0c22.1 0 40 17.9 40 40c0 5.3-1 10.5-3.1 1"
    "5.4L368 400 80 400 3.1 215.4C1 210.5 0 205.3 0 200c0-22.1 17.9-40 40-40l152 0 0-"
    "48-16 0c-17.7 0-32-14.3-32-32s14.3-32 32-32l16 0 0-16c0-17.7 14.3-32 32-32zM38.6"
    " 473.4L80 432l288 0 41.4 41.4c4.2 4.2 6.6 10 6.6 16c0 12.5-10.1 22.6-22.6 22.6L5"
    "4.6 512C42.1 512 32 501.9 32 489.4c0-6 2.4-11.8 6.6-16z\"/></svg>";
gfx::const_buffer_stream piece_chess_king
    ((const uint8_t*)piece_chess_king_data, 505);

static const char* piece_chess_king2_data = "<svg xmlns=\"http://www.w3.org/2000/svg\" "
    "viewBox=\"0 0 448 512\"><path d=\"M248 24c0-13.3-10.7-24-24-24s-24 10.7-24 24l0 32-"
    "32 0c-13.3 0-24 10.7-24 24s10.7 24 24 24l32 0 0 40L59.6 144C26.7 144 0 170.7 0 2"
    "03.6c0 8.2 1.7 16.3 4.9 23.8L59.1 352l52.3 0L49 208.2c-.6-1.5-1-3-1-4.6c0-6.4 5."
    "2-11.6 11.6-11.6L224 192l164.4 0c6.4 0 11.6 5.2 11.6 11.6c0 1.6-.3 3.2-1 4.6L336"
    ".5 352l52.3 0 54.2-124.6c3.3-7.5 4.9-15.6 4.9-23.8c0-32.9-26.7-59.6-59.6-59.6L24"
    "8 144l0-40 32 0c13.3 0 24-10.7 24-24s-10.7-24-24-24l-32 0 0-32zM101.2 432l245.6 "
    "0 16.6 32L84.7 464l16.6-32zm283.7-30.7c-5.5-10.6-16.5-17.3-28.4-17.3l-265 0c-12 "
    "0-22.9 6.7-28.4 17.3L36.6 452.5c-3 5.8-4.6 12.2-4.6 18.7C32 493.8 50.2 512 72.8 "
    "512l302.5 0c22.5 0 40.8-18.2 40.8-40.8c0-6.5-1.6-12.9-4.6-18.7l-26.5-51.2z\"/></s"
    "vg>";
gfx::const_buffer_stream piece_chess_king2
    ((const uint8_t*)piece_chess_king2_data, 763);

static const char* piece_chess_knight_data = "<svg xmlns=\"http://www.w3.org/2000/svg\""
    " viewBox=\"0 0 448 512\"><path d=\"M96 48L82.7 61.3C70.7 73.3 64 89.5 64 106.5l0 13"
    "2.4c0 10.7 5.3 20.7 14.2 26.6l10.6 7c14.3 9.6 32.7 10.7 48.1 3l3.2-1.6c2.6-1.3 5"
    "-2.8 7.3-4.5l49.4-37c6.6-5 15.7-5 22.3 0c10.2 7.7 9.9 23.1-.7 30.3L90.4 350C73.9"
    " 361.3 64 380 64 400l320 0 28.9-159c2.1-11.3 3.1-22.8 3.1-34.3l0-14.7C416 86 330"
    " 0 224 0L83.8 0C72.9 0 64 8.9 64 19.8c0 7.5 4.2 14.3 10.9 17.7L96 48zm24 68a20 2"
    "0 0 1 1 40 0 20 20 0 1 1 -40 0zM22.6 473.4c-4.2 4.2-6.6 10-6.6 16C16 501.9 26.1 "
    "512 38.6 512l370.7 0c12.5 0 22.6-10.1 22.6-22.6c0-6-2.4-11.8-6.6-16L384 432 64 4"
    "32 22.6 473.4z\"/></svg>";
gfx::const_buffer_stream piece_chess_knight
    ((const uint8_t*)piece_chess_knight_data, 622);

static const char* piece_chess_knight2_data = "<svg xmlns=\"http://www.w3.org/2000/svg"
    "\" viewBox=\"0 0 448 512\"><path d=\"M226.6 48L117.3 48l17.1 12.8c6 4.5 9.6 11.6 9.6"
    " 19.2s-3.6 14.7-9.6 19.2l-6.5 4.9c-10 7.5-16 19.3-16 31.9l-.3 91c0 10.2 4.9 19.9"
    " 13.2 25.8l1.9 1.3c9.9 7.1 23.3 7 33.2-.1l49.9-36.3c10.7-7.8 25.7-5.4 33.5 5.3s5"
    ".4 25.7-5.3 33.5l-49.9 36.3-53.8 39.1c-7.3 5.3-13 12.2-16.9 20.1l-50.7 0c5.3-22."
    "1 17.8-41.9 35.9-56.3c-1.3-.8-2.6-1.7-3.8-2.6L97 291.8c-21-15-33.4-39.2-33.3-65l"
    ".3-91c.1-19.8 6.7-38.7 18.6-53.9l-.4-.3C70.7 73 64 59.6 64 45.3C64 20.3 84.3 0 1"
    "09.3 0L226.6 0C331.2 0 416 84.8 416 189.4c0 11.1-1 22.2-2.9 33.2L390.1 352l-48.8"
    " 0 24.5-137.8c1.5-8.2 2.2-16.5 2.2-24.8C368 111.3 304.7 48 226.6 48zM85.2 432L68"
    ".7 464l310.7 0-16.6-32L85.2 432zm315.7-30.7l26.5 51.2c3 5.8 4.6 12.2 4.6 18.7c0 "
    "22.5-18.2 40.8-40.8 40.8L56.8 512C34.2 512 16 493.8 16 471.2c0-6.5 1.6-12.9 4.6-"
    "18.7l26.5-51.2C52.5 390.7 63.5 384 75.5 384l297 0c12 0 22.9 6.7 28.4 17.3zM172 1"
    "28a20 20 0 1 1 0 40 20 20 0 1 1 0-40z\"/></svg>";
gfx::const_buffer_stream piece_chess_knight2
    ((const uint8_t*)piece_chess_knight2_data, 964);

static const char* piece_chess_pawn_data = "<svg xmlns=\"http://www.w3.org/2000/svg\" v"
    "iewBox=\"0 0 320 512\"><path d=\"M215.5 224c29.2-18.4 48.5-50.9 48.5-88c0-57.4-46.6"
    "-104-104-104S56 78.6 56 136c0 37.1 19.4 69.6 48.5 88L96 224c-17.7 0-32 14.3-32 3"
    "2c0 16.5 12.5 30 28.5 31.8L80 400l160 0L227.5 287.8c16-1.8 28.5-15.3 28.5-31.8c0"
    "-17.7-14.3-32-32-32l-8.5 0zM22.6 473.4c-4.2 4.2-6.6 10-6.6 16C16 501.9 26.1 512 "
    "38.6 512l242.7 0c12.5 0 22.6-10.1 22.6-22.6c0-6-2.4-11.8-6.6-16L256 432 64 432 2"
    "2.6 473.4z\"/></svg>";
gfx::const_buffer_stream piece_chess_pawn
    ((const uint8_t*)piece_chess_pawn_data, 460);

static const char* piece_chess_pawn2_data = "<svg xmlns=\"http://www.w3.org/2000/svg\" "
    "viewBox=\"0 0 320 512\"><path d=\"M232 152A72 72 0 1 0 88 152a72 72 0 1 0 144 0zm24"
    " 120l-12.6 0 10.7 80-48.4 0L195 272l-35 0-35 0-10.7 80-48.4 0 10.7-80L64 272c-13"
    ".3 0-24-10.7-24-24s10.7-24 24-24c-15.1-20.1-24-45-24-72C40 85.7 93.7 32 160 32s1"
    "20 53.7 120 120c0 27-8.9 51.9-24 72c13.3 0 24 10.7 24 24s-10.7 24-24 24zM52.7 46"
    "4l214.7 0-16.6-32L69.2 432 52.7 464zm207.9-80c12 0 22.9 6.7 28.4 17.3l26.5 51.2c"
    "3 5.8 4.6 12.2 4.6 18.7c0 22.5-18.2 40.8-40.8 40.8L40.8 512C18.2 512 0 493.8 0 4"
    "71.2c0-6.5 1.6-12.9 4.6-18.7l26.5-51.2C36.5 390.7 47.5 384 59.5 384l201 0z\"/></s"
    "vg>";
gfx::const_buffer_stream piece_chess_pawn2
    ((const uint8_t*)piece_chess_pawn2_data, 603);

static const char* piece_chess_queen_data = "<svg xmlns=\"http://www.w3.org/2000/svg\" "
    "viewBox=\"0 0 512 512\"><path d=\"M256 0a56 56 0 1 1 0 112A56 56 0 1 1 256 0zM134.1"
    " 143.8c3.3-13 15-23.8 30.2-23.8c12.3 0 22.6 7.2 27.7 17c12 23.2 36.2 39 64 39s52"
    "-15.8 64-39c5.1-9.8 15.4-17 27.7-17c15.3 0 27 10.8 30.2 23.8c7 27.8 32.2 48.3 62"
    ".1 48.3c10.8 0 21-2.7 29.8-7.4c8.4-4.4 18.9-4.5 27.6 .9c13 8 17.1 25 9.2 38L399."
    "7 400 384 400l-40.4 0-175.1 0L128 400l-15.7 0L5.4 223.6c-7.9-13-3.8-30 9.2-38c8."
    "7-5.3 19.2-5.3 27.6-.9c8.9 4.7 19 7.4 29.8 7.4c29.9 0 55.1-20.5 62.1-48.3zM256 2"
    "24s0 0 0 0s0 0 0 0s0 0 0 0zM112 432l288 0 41.4 41.4c4.2 4.2 6.6 10 6.6 16c0 12.5"
    "-10.1 22.6-22.6 22.6L86.6 512C74.1 512 64 501.9 64 489.4c0-6 2.4-11.8 6.6-16L112"
    " 432z\"/></svg>";
gfx::const_buffer_stream piece_chess_queen
    ((const uint8_t*)piece_chess_queen_data, 694);

static const char* piece_chess_queen2_data = "<svg xmlns=\"http://www.w3.org/2000/svg\""
    " viewBox=\"0 0 512 512\"><path d=\"M256 96a48 48 0 1 0 0-96 48 48 0 1 0 0 96zm-95.2"
    "-8c-18.1 0-31.3 12.8-35.6 26.9c-8 26.2-32.4 45.2-61.2 45.2c-10 0-19.4-2.3-27.7-6"
    ".3c-7.6-3.7-16.7-3.3-24 1.2C.7 162.1-3.1 177.1 3.7 188.9L97.6 352l55.4 0-83-144."
    "1c40.5-2.2 75.3-25.9 93.1-59.8c22 26.8 55.4 43.9 92.8 43.9s70.8-17.1 92.8-43.9c1"
    "7.8 34 52.6 57.7 93.1 59.8L359 352l55.4 0 93.9-163.1c6.8-11.7 3-26.7-8.6-33.8c-7"
    ".3-4.5-16.4-4.9-24-1.2c-8.4 4-17.7 6.3-27.7 6.3c-28.8 0-53.2-19-61.2-45.2C382.5 "
    "100.8 369.3 88 351.2 88c-14.5 0-26.3 8.5-32.4 19.3c-12.4 22-35.9 36.7-62.8 36.7s"
    "-50.4-14.8-62.8-36.7C187.1 96.5 175.4 88 160.8 88zM133.2 432l245.6 0 16.6 32-278"
    ".7 0 16.6-32zm283.7-30.7c-5.5-10.6-16.5-17.3-28.4-17.3l-265 0c-12 0-22.9 6.7-28."
    "4 17.3L68.6 452.5c-3 5.8-4.6 12.2-4.6 18.7c0 22.5 18.2 40.8 40.8 40.8l302.5 0c22"
    ".5 0 40.8-18.2 40.8-40.8c0-6.5-1.6-12.9-4.6-18.7l-26.5-51.2z\"/></svg>";
gfx::const_buffer_stream piece_chess_queen2
    ((const uint8_t*)piece_chess_queen2_data, 908);

static const char* piece_chess_rook_data = "<svg xmlns=\"http://www.w3.org/2000/svg\" v"
    "iewBox=\"0 0 448 512\"><path d=\"M32 192L32 48c0-8.8 7.2-16 16-16l64 0c8.8 0 16 7.2"
    " 16 16l0 40c0 4.4 3.6 8 8 8l32 0c4.4 0 8-3.6 8-8l0-40c0-8.8 7.2-16 16-16l64 0c8."
    "8 0 16 7.2 16 16l0 40c0 4.4 3.6 8 8 8l32 0c4.4 0 8-3.6 8-8l0-40c0-8.8 7.2-16 16-"
    "16l64 0c8.8 0 16 7.2 16 16l0 144c0 10.1-4.7 19.6-12.8 25.6L352 256l16 144L80 400"
    " 96 256 44.8 217.6C36.7 211.6 32 202.1 32 192zm176 96l32 0c8.8 0 16-7.2 16-16l0-"
    "48c0-17.7-14.3-32-32-32s-32 14.3-32 32l0 48c0 8.8 7.2 16 16 16zM22.6 473.4L64 43"
    "2l320 0 41.4 41.4c4.2 4.2 6.6 10 6.6 16c0 12.5-10.1 22.6-22.6 22.6L38.6 512C26.1"
    " 512 16 501.9 16 489.4c0-6 2.4-11.8 6.6-16z\"/></svg>";
gfx::const_buffer_stream piece_chess_rook
    ((const uint8_t*)piece_chess_rook_data, 653);

static const char* piece_chess_rook2_data = "<svg xmlns=\"http://www.w3.org/2000/svg\" "
    "viewBox=\"0 0 448 512\"><path d=\"M80 80l0 112c0 2.5 1.2 4.9 3.2 6.4l51.2 38.4c6.8 "
    "5.1 10.4 13.4 9.5 21.9L133.5 352l-48.3 0 9.4-85L54.4 236.8C40.3 226.2 32 209.6 3"
    "2 192L32 72c0-22.1 17.9-40 40-40l304 0c22.1 0 40 17.9 40 40l0 120c0 17.6-8.3 34."
    "2-22.4 44.8L353.4 267l9.4 85-48.3 0-10.4-93.3c-.9-8.4 2.7-16.8 9.5-21.9l51.2-38."
    "4c2-1.5 3.2-3.9 3.2-6.4l0-112-64 0 0 24c0 13.3-10.7 24-24 24s-24-10.7-24-24l0-24"
    "-64 0 0 24c0 13.3-10.7 24-24 24s-24-10.7-24-24l0-24L80 80zm4.7 384l278.7 0-16.6-"
    "32-245.6 0L84.7 464zm271.9-80c12 0 22.9 6.7 28.4 17.3l26.5 51.2c3 5.8 4.6 12.2 4"
    ".6 18.7c0 22.5-18.2 40.8-40.8 40.8L72.8 512C50.2 512 32 493.8 32 471.2c0-6.5 1.6"
    "-12.9 4.6-18.7l26.5-51.2C68.5 390.7 79.5 384 91.5 384l265 0zM208 288c-8.8 0-16-7"
    ".2-16-16l0-48c0-17.7 14.3-32 32-32s32 14.3 32 32l0 48c0 8.8-7.2 16-16 16l-32 0z\""
    "/></svg>";
gfx::const_buffer_stream piece_chess_rook2
    ((const uint8_t*)piece_chess_rook2_data, 848);
#endif // PIECE_IMPLEMENTATION
