// Automatically generated by https://honeythecodewitch.com/gfx/icon-pack
// #define POWER_IMPLEMENTATION in exactly one
// translation unit (.cpp file) before including this header
#ifndef POWER_HPP
#define POWER_HPP
#include <stdint.h>
#include <stddef.h>
#include "gfx_core.hpp"
#include "gfx_positioning.hpp"

constexpr static const uint16_t power_height = 32;

/// @brief "Power Off" dimensions
constexpr static const gfx::sizef power_power_off_dimensions(512,512);
/// @brief "Power Off" scaled dimensions
constexpr static const gfx::size16 power_power_off_scaled_dimensions(32,32);
/// @brief "Power Off" target scale
constexpr static const float power_power_off_scale = 0.0625;
/// @brief "Power Off" - a SVG vector icon
extern gfx::const_buffer_stream power_power_off;
#endif // POWER_HPP

#ifdef POWER_IMPLEMENTATION
static const char* power_power_off_data = "<svg xmlns=\"http://www.w3.org/2000/svg\" vi"
    "ewBox=\"0 0 512 512\"><path d=\"M288 32c0-17.7-14.3-32-32-32s-32 14.3-32 32l0 224c0"
    " 17.7 14.3 32 32 32s32-14.3 32-32l0-224zM143.5 120.6c13.6-11.3 15.4-31.5 4.1-45."
    "1s-31.5-15.4-45.1-4.1C49.7 115.4 16 181.8 16 256c0 132.5 107.5 240 240 240s240-1"
    "07.5 240-240c0-74.2-33.8-140.6-86.6-184.6c-13.6-11.3-33.8-9.4-45.1 4.1s-9.4 33.8"
    " 4.1 45.1c38.9 32.3 63.5 81 63.5 135.4c0 97.2-78.8 176-176 176s-176-78.8-176-176"
    "c0-54.4 24.7-103.1 63.5-135.4z\"/></svg>";
gfx::const_buffer_stream power_power_off
    ((const uint8_t*)power_power_off_data, 481);
#endif // POWER_IMPLEMENTATION
